[window]
opacity = 0.80

[window.padding]
x = 10
y = 10

[font]
size = 14

[font.normal]
family = 'Zed Mono Extended'
style  = "Normal"

[font.bold]
family = 'Zed Mono Extended'
style  = "Bold"

[font.italic]
family = 'Zed Mono Extended'
style  = "Italic"

[colors.cursor]
text   = "#282828"
cursor = "#ebdbb2"

[colors.primary]
background = '#282828'
foreground = '#ebdbb2'

[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'
