[window]
opacity = 0.85

[window.padding]
x = 10
y = 10

[font]
size = 12

[font.normal]
family = 'FiraCode Nerd Font'
style = "Normal"

[font.bold]
family = 'FiraCode Nerd Font'
style = "Bold"

[font.italic]
family = 'FiraCode Nerd Font'
style = "Italic"

[font.bold_italic]
family = 'FiraCode Nerd Font'

[colors.cursor]
text = "#e0def4"
cursor = "#56526e"

